name: Radio
version: 0.1
main: org.covertlizard.bukkit.plugin.radio.RadioPlugin
commands:
    radio:
        description: The main radio command
        usage: /radio <args>
        permission: radio.basic
permissions:
    radio.*:
        description: Gives access to all radio commands.
        children:
            radio.basic: true
            radio.use: true
            radio.pause: true
            radio.reload: true
            radio.stop.*: true
    radio.stop.*:
        description: Gives access to all stop commands
        default: op
    radio.reload:
        description: Reloads the radio plugin
        default: op
    radio.pause:
        description: Allows you to pause a music station
        default: op
    radio.stop:
        description: Allows you to stop a music station
        default: op
    radio.stop.all:
        description: Allows you to stop all music stations
        default: op
    radio.start:
        description: Allows you to start a music station
        default: op
    radio.start.all:
        description: Allows you to start all music stations
        default: op
    radio.basic:
        description: Allows players to use the radio command
        default: op
    radio.use:
        description: Allows players to use the radio
        default: true